prgrms-be-devcourse/NBE6-8-1-Team14

- frontend/.gitignore
프론트엔드 측에서 로컬 테스트를 위해 .gitignore 파일을 갱신합니다
현재 빌드업 중인 관계로 백엔드와 프론트 간 실질적으로 통신하기 어려운 상황입니다.
그래서 프론트의 로컬 상에 더미데이터를 추가하여 테스트 해볼 수 있도록 frontend/public 폴더에 test 폴더를 만들 예정입니다.
다만, commit에 직접 반영되는 것을 막고자 .gitignore의 변경 및 PR을 제출하게 되었습니다.
> chore/fe: 로컬 테스트를 위한 test 폴더를 gitignore에 추가

- backend/src/main/java/com/back/GridsAndCirclesApplication.java
- backend/src/main/java/com/back/domain/cart/entity/Cart.java
- backend/src/main/java/com/back/domain/cart/entity/CartItem.java
- backend/src/main/java/com/back/domain/delivery/entity/Delivery.java
- backend/src/main/java/com/back/domain/delivery/enums/DeliveryStatus.java
- backend/src/main/java/com/back/domain/member/entity/Member.java
- backend/src/main/java/com/back/domain/member/enums/Role.java
- backend/src/main/java/com/back/domain/order/entity/Order.java
- backend/src/main/java/com/back/domain/order/entity/OrderItem.java
- backend/src/main/java/com/back/domain/product/entity/Product.java
- backend/src/main/java/com/back/domain/product/entity/Stock.java
- backend/src/main/java/com/back/domain/product/enums/StockStatus.java
- backend/src/main/java/com/back/global/dev/DevController.java
- backend/src/main/java/com/back/global/jwt/refreshtoken/entity/RefreshToken.java
- backend/src/main/resources/application.yml
기본 엔티티 구현 및 db 관련 재설정
- 추가적으로 필요한 엔티티 내 메서드 등은 구현하면서 작성하시면 됩니다.
- mysql 도커 컨테이너로 DB 테이블 정상 생성 되는 것 확인하였습니다
closed #5
> feat/be: 기본 엔티티 구현 및 db 관련 재설정

- backend/src/main/java/com/back/domain/member/service/MemberService.java
회원가입 기능 및 Security 요청사항 수정
closed #13
> fix/be: 회원가입 기능 및 Security 요청사항 수정

- backend/src/main/java/com/back/domain/cart/controller/CartController.java
- backend/src/main/java/com/back/domain/cart/dto/request/CartItemRequestDto.java
- backend/src/main/java/com/back/domain/cart/dto/request/CartRequestDto.java
- backend/src/main/java/com/back/domain/cart/dto/response/CartItemResponseDto.java
- backend/src/main/java/com/back/domain/cart/dto/response/CartResponseDto.java
- backend/src/main/java/com/back/domain/cart/entity/Cart.java
- backend/src/main/java/com/back/domain/cart/entity/CartItem.java
- backend/src/main/java/com/back/domain/cart/exception/CartErrorCode.java
- backend/src/main/java/com/back/domain/cart/exception/CartException.java
- backend/src/main/java/com/back/domain/cart/repository/CartItemRepository.java
- backend/src/main/java/com/back/domain/cart/repository/CartRepository.java
- backend/src/main/java/com/back/domain/cart/service/CartService.java
- backend/src/main/java/com/back/domain/member/entity/Member.java
- backend/src/main/java/com/back/domain/order/entity/OrderItem.java
- backend/src/main/java/com/back/domain/order/service/OrderService.java
장바구니 기능 구현
- DTO 클래스 Record 및 of/from 메서드 활용하여 리팩토링 할 예정
- 일부 일정상/구현 편의를 위해 불필요한 부분은 생략함 (장바구니에서 갯수 조절, 장바구니에서 선택 주문 가능 기능 등은 배제)
closed #18
> feat/be: 장바구니 기능 구현

- backend/src/main/java/com/back/domain/cart/dto/response/CartItemResponseDto.java
- backend/src/main/java/com/back/domain/cart/dto/response/CartResponseDto.java
- backend/src/main/java/com/back/domain/cart/service/CartService.java
- backend/src/main/java/com/back/domain/order/dto/request/OrderBaseAddressRequestDto.java
- backend/src/main/java/com/back/domain/order/dto/request/OrderItemRequestDto.java
- backend/src/main/java/com/back/domain/order/dto/request/OrderRequestDto.java
- backend/src/main/java/com/back/domain/order/dto/response/OrderItemResponseDto.java
- backend/src/main/java/com/back/domain/order/dto/response/OrderResponseDto.java
- backend/src/main/java/com/back/domain/order/service/OrderService.java
dto 클래스에서 record로 변경 및 from 메서드 활용
- 
closed #24
> refactor/be: dto 클래스에서 record로 변경 및 from 메서드 활용

- backend/src/main/java/com/back/domain/member/controller/MemberController.java
- backend/src/main/java/com/back/domain/member/dto/MemberDto.java
- backend/src/main/java/com/back/domain/member/entity/Member.java
- backend/src/main/java/com/back/domain/member/service/MemberService.java
- backend/src/main/java/com/back/global/config/KeyConfig.java
- backend/src/main/java/com/back/global/jwt/authtoken/service/AuthTokenService.java
- backend/src/main/java/com/back/global/jwt/refreshtoken/entity/RefreshToken.java
- backend/src/main/java/com/back/global/jwt/refreshtoken/repository/RefreshTokenRepository.java
- backend/src/main/resources/application.yml
리프레시 토큰을 생성하여 회원가입 기능 구현
// 예시
closed #15
> feat/be: 리프레시 토큰을 생성하여 회원가입 기능 구현

- frontend/src/app/auth/signup/page.tsx
패키지 임포트 수정
- #32 와 동일한 잠재적 문제가 있습니다
closed #33
> chore/fe: 패키지 임포트 수정

- backend/src/main/java/com/back/domain/cart/controller/CartController.java
- backend/src/main/java/com/back/domain/cart/repository/CartRepository.java
- backend/src/main/java/com/back/domain/cart/service/CartService.java
장바구니 조회/삭제 멤버 아이디 기준으로 수정
// 예시
closed #47
> fix/be: 장바구니 조회/삭제 멤버 아이디 기준으로 수정

- backend/src/main/java/com/back/domain/member/controller/MemberController.java
- backend/src/main/java/com/back/domain/product/controller/ProductController.java
- backend/src/main/java/com/back/domain/product/dto/ProductDto.java
- backend/src/main/java/com/back/domain/product/dto/ProductRequestDto.java
- backend/src/main/java/com/back/domain/product/dto/ProductUpdateRequestDto.java
- backend/src/main/java/com/back/domain/product/entity/Product.java
- backend/src/main/java/com/back/domain/product/service/ProductService.java
- backend/src/main/java/com/back/global/jwt/authtoken/service/AuthTokenService.java
상품 CRUD 구현
- 권한 체크 부분은 구현 예정입니다
closed #49
> feat/be: 상품 CRUD 구현

- backend/src/main/java/com/back/domain/cart/controller/CartController.java
- backend/src/main/java/com/back/domain/delivery/controller/DeliveryController.java
- backend/src/main/java/com/back/domain/member/controller/AdminController.java
- backend/src/main/java/com/back/domain/member/dto/response/AdminViewerResponseDto.java
- backend/src/main/java/com/back/domain/member/exception/MemberErrorCode.java
- backend/src/main/java/com/back/domain/member/service/AdminService.java
- backend/src/main/java/com/back/domain/order/controller/OrderController.java
- backend/src/main/java/com/back/domain/order/dto/response/OrderResponseDto.java
- backend/src/main/java/com/back/domain/order/repository/OrderRepository.java
관리자 페이지 주문+배송 내역 조회 구현
closed #56
> feat/be: 관리자 페이지 주문+배송 내역 조회 구현

- backend/src/main/java/com/back/domain/order/controller/OrderController.java
- backend/src/main/java/com/back/domain/order/dto/response/OrderSimpleResponseDto.java
- backend/src/main/java/com/back/domain/order/repository/OrderRepository.java
- backend/src/main/java/com/back/domain/order/service/OrderService.java
- backend/src/main/resources/application.yml
회원 한 명에 대한 모든 주문 내역 조회 구현
closed #
> feat/be: 회원 한 명 모든 주문 내역 조회 구현

- backend/src/main/java/com/back/domain/member/controller/AdminController.java
- backend/src/main/java/com/back/domain/member/dto/response/AdminDetailResponseDto.java
- backend/src/main/java/com/back/domain/member/dto/response/AdminViewerResponseDto.java
- backend/src/main/java/com/back/domain/member/service/AdminService.java
- backend/src/main/java/com/back/domain/order/dto/response/OrderSimpleResponseDto.java
어드민 간소화 버전 및 상세 버전 분리
closed #
> fix/be: 어드민 간소화 버전 및 상세 버전 분리

- backend/src/main/java/com/back/global/security/SecurityConfig.java
> feat/be: cors 설정 추가

- backend/src/main/java/com/back/domain/member/service/MemberService.java
> fix/be 쿠키 수정 사항 반영

- backend/src/main/java/com/back/domain/member/controller/MemberController.java
- backend/src/main/java/com/back/domain/member/dto/request/MemberJoinRequestDto.java
- backend/src/main/java/com/back/domain/member/dto/request/MemberLoginRequestDto.java
- backend/src/main/java/com/back/domain/member/dto/response/MemberLoginResponseDto.java
- backend/src/main/java/com/back/global/config/SwaggerConfig.java
- backend/src/main/java/com/back/global/jwt/authtoken/config/JwtAuthenticationFilter.java
- backend/src/main/java/com/back/global/security/SecurityConfig.java
- backend/src/main/resources/application.yml
복잡한 충돌 브랜치 로컬 병합
- 죄송합니다 명령어 하나 잘못쳐서 브랜치를 새로 파버렸어요..
closed #
> fix/be: 복잡한 충돌 브랜치 로컬 병합

- frontend/package-lock.json
- frontend/package.json
- frontend/src/hooks/useAuth.tsx
- frontend/src/lib/backend/client.ts
useAuth, client 추가 및 의존성 추가
1. useAuth 컴포넌트 초안 작성 완료하였습니다.
2. backend와 통신 목적으로 client 파일을 추가했습니다.
3. dto의 수정이 계속 이루어질 수 있기 때문에 schema 파일은 pr 대상에서 제외했습니다. 개인적으로 실시해주시고 더는 없다면 pr을 넣으면 될 것 같습니다
- BE 쪽에 구현이 완전하지 부분이 있어 머지 후 파일 확인 시 에러 출력이 있을 수 있습니다.
#62
> Feature/fe: useAuth, client 추가 및 의존성 추가

- backend/src/main/java/com/back/domain/member/controller/MemberController.java
- backend/src/main/java/com/back/domain/member/dto/MemberValidTokenResponseDto.java
- backend/src/main/java/com/back/domain/member/service/MemberService.java
- backend/src/main/java/com/back/global/exception/ErrorCode.java
- backend/src/main/java/com/back/global/jwt/cookie/CookieConfig.java
- backend/src/main/java/com/back/global/jwt/refreshtoken/repository/RefreshTokenRepository.java
> feat/be: 토큰 유효성 검사 구현

- backend/build.gradle.kts
- backend/src/main/java/com/back/GridsAndCirclesApplication.java
- backend/src/main/java/com/back/domain/member/controller/MemberController.java
- backend/src/main/java/com/back/domain/member/dto/response/MemberValidTokenResponseDto.java
- backend/src/main/java/com/back/domain/member/service/MemberService.java
- backend/src/main/java/com/back/global/jwt/refreshtoken/repository/RefreshTokenRepository.java
로그아웃 수정, 리프레시 토큰 수정, Dotenv 버그 수정
closed #81
> fix/be 로그아웃 수정, 리프레시 토큰 수정, Dotenv 버그 수정

- frontend/src/app/ClientLayout.tsx
- frontend/src/app/ContextLayout.tsx
- frontend/src/app/layout.tsx
- frontend/src/app/page.tsx
- frontend/src/components/dev/auth/DevRoleSwitcher.tsx
- frontend/src/components/header/header.tsx
- frontend/src/components/product/card.tsx
- frontend/src/hooks/useAuth.tsx
- frontend/src/types/auth.ts
컴포넌트 수정 및 변경
실제 user부분 DTO를 활용하기 위해 회원과 관련된 부분을 일부 수정하거나 추가하였습니다
src 폴더 기준으로 경로를 적어놨습니다.
1. 추가
2. 수정
3. 미구현
- 실제로 작동하지 않을 수도 있습니다.
- 사용 중에 문제 발견해주시면 말씀주세요!
#62
#82
> Feature/fe: 컴포넌트 수정 및 변경

- frontend/src/app/cart/page.tsx
- frontend/src/app/payment/page.tsx
- frontend/src/app/products/[id]/page.tsx
- frontend/src/types/dev/payment.ts
구매하기 페이지 구현
- 코드에서 특별히 설명해야 할 부분 (주석 등으로 드러나지 않는 부분)
- 코드 리뷰를 특별히 요청하고 싶은 부분
closed #45
> [FEATURE / FE] 구매하기 페이지 구현

- frontend/src/app/ClientLayout.tsx
- frontend/src/components/footer/footer.tsx
> [FEATURE / FE] 푸터 구현

- backend/src/main/java/com/back/domain/member/controller/MemberController.java
- backend/src/main/java/com/back/domain/member/dto/request/MemberInfoUpdateRequestDto.java
- backend/src/main/java/com/back/domain/member/dto/response/MemberInfoResponseDto.java
- backend/src/main/java/com/back/domain/member/dto/response/MemberInfoUpdateResponseDto.java
- backend/src/main/java/com/back/domain/member/entity/Member.java
- backend/src/main/java/com/back/domain/member/service/MemberService.java
- backend/src/main/java/com/back/global/jwt/authtoken/service/AuthTokenService.java
- backend/src/main/java/com/back/global/jwt/refreshtoken/repository/RefreshTokenRepository.java
회원 정보 조회 및 수정구현
closed #77
closed #78
> feat/be: 회원 정보 조회 및 수정 구현

- backend/src/main/java/com/back/global/jwt/authtoken/config/JwtAuthenticationFilter.java
- backend/src/main/java/com/back/global/security/SecurityConfig.java
> feat/be: 개발용으로 모든 엔드포인트 허용

- backend/src/main/java/com/back/domain/cart/service/CartService.java
- backend/src/main/java/com/back/domain/delivery/service/DeliveryService.java
- backend/src/main/java/com/back/global/exception/GlobalExceptionHandler.java
> feat/be: 각종 구현 수정

- backend/src/main/java/com/back/domain/product/controller/ProductController.java
- backend/src/main/java/com/back/domain/product/dto/ProductDto.java
- backend/src/main/java/com/back/domain/product/dto/ProductRequestDto.java
- backend/src/main/java/com/back/domain/product/dto/StockDto.java
- backend/src/main/java/com/back/domain/product/entity/Product.java
- backend/src/main/java/com/back/domain/product/repository/StockRepository.java
- backend/src/main/java/com/back/domain/product/service/ProductService.java
상품 등록, 조회 시 재고 현황 출력 기능 구현
closed #98
> feat/be: 상품 등록, 조회 시 재고 현황 출력 기능 구현

- backend/src/main/java/com/back/global/jwt/cookie/CookieConfig.java
> fix: 잘못된 cookie config 수정
